UI/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using System.Net;

namespace UI.Controllers
{
    /* ----------------------------------------------
      * Area Related Actions:
      * - List all areas including locales
      * - Add an area
      * - Modify an area
      * - Hide an area
      * ----------------------------------------------
     */

    
    public class AreaController : Controller
    {
        private readonly AreaDbService _area = new AreaDbService();
        private readonly LocationDbService _loc = new LocationDbService();
        // GET: Area/List
        [UserAuthorization("admin")]
        public ActionResult List()
        {
            return View(_area.GetAreaList());
        }

        // GET: Area/Add
        [UserAuthorization("admin")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Area/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Add([Bind(Include = "Id,Name,ShortName")] Area area)
        {
            if (ModelState.IsValid)
            {
                if (_area.AlreadyhastheName(area))
                 {
                    ViewBag.error = "This area already been added, please try to add another area.";
                    return View(area);
                 }
                if (_area.AlreadyhastheShortName(area))
                 {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(area);
                 }
                _area.AddArea(area);
                return RedirectToAction("List");
            }
            return View(area);
        }

        // GET: Area/Modify/5
        [UserAuthorization("admin")]
        public ActionResult Modify(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = _area.GetArea(id.Value);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        //POST: Area/Modify/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Modify([Bind(Include = "Id,Name,ShortName")] Area area)
        {
            if (ModelState.IsValid)
            {

                if (_area.AlreadyhastheName(area))
                {
                    ViewBag.error = "This area already been added, please try to add another area.";
                    return View(area);
                }
                if (_area.AlreadyhastheShortName(area))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(area);
                }
                _area.ModifyArea(area);
                return RedirectToAction("List");
            }
            return View(area);
        }

        // GET: Area/Hide/5
        [UserAuthorization("admin")]
        public ActionResult Hide(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = _area.GetArea(id.Value);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Area/Hide/5
        [HttpPost, ActionName("Hide")]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult HideConfirmed(int id)
        {
            _area.HideArea(id);
            return RedirectToAction("List");
        }

        [UserAuthorization("user")]
        public JsonResult GetSubList(int id)
        {
            var locationList = _loc.GetLocationList(id);
            var data = locationList.Select(loc => new LocationViewModels { Id = loc.Id, Name = loc.Name });
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace UI.Controllers
{
    /* -------------------------------
     * Post Related Actions:
     * - List current user's posts
     * - View a post
     * - Create a post
     * - Modify a post
     * - Delete a post
     * -------------------------------
    */
    public class PostController : Controller
    {
        private readonly PostDbService _post_svc = new PostDbService();
        private readonly AreaDbService _area_svc = new AreaDbService();
        private readonly LocationDbService _loc_svc = new LocationDbService();
        private readonly CategoryDbService _cat_svc = new CategoryDbService();
        private readonly SubcategoryDbService _sub_svc = new SubcategoryDbService();
        private readonly UserDbService _user_svc = new UserDbService();

        private void GenerateViewBagData()
        {
            var categoryList = _cat_svc.GetCategoryList();
            var subcategoryList = _sub_svc.GetSubcategoryListByCat(categoryList.First().Id);
            var areaList = _area_svc.GetAreaList();
            var localeList = _loc_svc.GetLocationList(areaList.First().Id);
            ViewBag.categoryList = categoryList;
            ViewBag.subcatList = subcategoryList;
            ViewBag.areaList = areaList;
            ViewBag.localeList = localeList;
        }


        // GET: Post/Index?category=category1&(subcategory=subcategory1)&area=ny&locale=bronx
        public ActionResult ListAll(string category, string subcategory, string area, string locale, int page = 1)
        {
            var areaList = _area_svc.GetAreaList();
            var categoryList = _cat_svc.GetCategoryList();
            ICollection<Location> localeList = new List<Location>();
            ICollection<Subcategory> subcatList = new List<Subcategory>();

            // Assign default value to query value if it is null
            if (categoryList.Any())
            {
                category = category ?? categoryList.First().ShortName;
                var catObj = categoryList.Where(cat => cat.ShortName == category).FirstOrDefault();
                if (catObj == null)
                {
                    return HttpNotFound();
                }
                subcatList = _sub_svc.GetSubcategoryListByCatWithAll(catObj.Id);
                if (subcatList.Any())
                {
                    subcategory = subcategory ?? subcatList.First().ShortName;
                }
            }           

            if (areaList.Any())
            {
                area = area ?? areaList.First().ShortName;
                var areaObj = areaList.Where(a => a.ShortName == area).FirstOrDefault();
                if (areaObj == null)
                {
                    return HttpNotFound();
                }
                localeList = _loc_svc.GetLocListWithAll(areaObj.Id);
                if (localeList.Any())
                {
                    locale = locale ?? localeList.First().ShortName;
                } 
            }

            var postList = _post_svc.GetPost(area, locale, category, subcategory).ToPagedList(page, 10);

            var viewModel = new CategoriesViewModels
            {
                AreaList = areaList,
                LocationList = localeList,
                CategoryList = categoryList,
                SubcategoryList = subcatList,
                PostList = postList,
                SelectedArea = area,
                SelectedLocation = locale,
                SelectedCategory = category,
                SelectedSubcategory = subcategory
            };
            if (Request.IsAjaxRequest())
            {
                return PartialView("posts", viewModel);
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ListAll([Bind(Include = "SelectedArea,SelectedLocation,SelectedCategory,SelectedSubcategory,LocationList,SubcategoryList")] CategoriesViewModels model)
        {
            model.AreaList = _area_svc.GetAreaList();
            model.CategoryList = _cat_svc.GetCategoryList();
            var selectedArea = model.AreaList.Where(area => area.ShortName == model.SelectedArea).First();
            var locationList = _loc_svc.GetLocListWithAll(selectedArea.Id); 
            model.LocationList = locationList.OrderBy(loc => loc.Name).ToList();
            model.SelectedLocation = model.SelectedLocation ?? model.LocationList.First().ShortName;
            var selectedCat = model.CategoryList.Where(cat => cat.ShortName == model.SelectedCategory).First();
            var subcatList = _sub_svc.GetSubcategoryListByCatWithAll(selectedCat.Id);
            model.SubcategoryList = subcatList;
            model.SelectedSubcategory = model.SelectedSubcategory ?? subcatList.First().ShortName;
            var postList = _post_svc.GetPost(model.SelectedArea, model.SelectedLocation, model.SelectedCategory, model.SelectedSubcategory).ToPagedList(1, 10);
            model.PostList = postList;
            return View(model);
        }

        private PostDbService _postService = new PostDbService();
        private CategoryDbService _categoryService = new CategoryDbService();
        [UserAuthorization("admin")]
        public ActionResult Hide(int post_id, string user_id)
        {
            Post post = _postService.GetPost(post_id);
            post.IsHidden = true;
            _postService.UpdatePost(post_id, post);
            return RedirectToAction("List", new { user_id = user_id });
        }

        [Authorize]
        [Route("Post/List/{user_id}/{sort_order?}")]
        public ActionResult List(string user_id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (user_id == User.Identity.GetUserId())
            {
                ViewBag.isForAdmin = false;
            } else
            {
                ViewBag.isForAdmin = true;
            }
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var posts = _postService.GetPostByUser(user_id);
            if (!String.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(s => 
                                        s.Title.Contains(searchString)
                                       || s.Author.Email.Contains(searchString)
                                       || s.Subcategory.Name.Contains(searchString)
                                       || s.Subcategory.Category.Name.Contains(searchString)
                                       );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    posts = posts.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    posts = posts.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    posts = posts.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(posts.ToPagedList(pageNumber, pageSize));
        }



        // GET: Post
        [UserAuthorization("user")]
        //[Route("Post/List/{user_id}")]
        public ActionResult ListOld(string user_id)
        {
            var posts = _postService.GetPostListByUser(user_id);
            if (user_id == User.Identity.GetUserId())
            {
                ViewBag.isForAdmin = false;
            } else
            {
                ViewBag.isForAdmin = true;
            }
            return View(posts);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = _post_svc.GetPost(id.Value);
            var location = _loc_svc.GetLocation(post.LocationId);
            var area = _area_svc.GetArea(location.AreaId);
            var category = _cat_svc.GetCategory(post.CategoryId);
            var subcategory = _sub_svc.GetSubcategory(post.SubcategoryId, post.CategoryId);
            var user = _user_svc.GetUser(post.AuthorId);
            ViewBag.area = area.ShortName;
            ViewBag.locale = location.ShortName;
            ViewBag.category = category.ShortName;
            ViewBag.subcategory = subcategory.ShortName;
            ViewBag.username = user.UserName;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        public ActionResult DetailsForPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = _post_svc.GetPost(id.Value);
            var location = _loc_svc.GetLocation(post.LocationId);
            var area = _area_svc.GetArea(location.AreaId);
            var category = _cat_svc.GetCategory(post.CategoryId);
            var subcategory = _sub_svc.GetSubcategory(post.SubcategoryId, post.CategoryId);
            var user = _user_svc.GetUser(post.AuthorId);
            ViewBag.area = area.ShortName;
            ViewBag.locale = location.ShortName;
            ViewBag.category = category.ShortName;

UI/Views/Shared/Posts.cshtml
@using PagedList.Mvc
@model Data.Models.CategoriesViewModels
@{
    ViewBag.Title = "Posts";
}


<div id="postlist">
    <table class="table">
        @foreach (var item in Model.PostList)
        {
            <tr>
                <td>
                    <text class="text-muted">@item.Timestamp.ToShortDateString()</text>   @Html.ActionLink(item.Title, "Details", "Post", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </table>

    @Html.PagedListPager(
        Model.PostList,
        page => Url.Action("ListAll", "Post", new { category = Model.SelectedCategory, subcategory = Model.SelectedSubcategory, area = Model.SelectedArea, locale = Model.SelectedLocation, page =page }),
        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
            new PagedListRenderOptions
            {
                Display = PagedListDisplayMode.IfNeeded,
                MaximumPageNumbersToDisplay = 5,
            },
            new AjaxOptions()
            {
                HttpMethod = "GET",
                UpdateTargetId = "postlist"
            }
        )
    )
</div>

UI/Views/Shared/_AdminPanel.cshtml
@using Microsoft.AspNet.Identity;
@using DB.Database
@{
    var userId = User.Identity.GetUserId();
    var user_svc = new UserDbService();
}

@if (userId != null && user_svc.GetUser(userId).IsAdmin)
{
    <div class="btn-group admin-btn">
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Administration <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("User Administration", "List", "Account")</li>
            <li>@Html.ActionLink("Category Administration", "List", "Category")</li>
            <li>@Html.ActionLink("Area Administration", "List", "Area")</li>
        </ul>
    </div>
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mini Craigslist", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Home", "Index", "Account")</li>
                </ul>
                @Html.Partial("_LoginPartial")
                @Html.Partial("_AdminPanel")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UI/Views/Shared/_Modal.cshtml
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "anti-forgery-form" }))
            {
                @Html.AntiForgeryToken()
            }
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="confirm-btn" type="button" class="btn btn-primary">
                    Hide
                </button>
            </div>
        </div>
    </div>
</div>