UI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using Data.Models;
using DB.Database;

namespace UI.Controllers
{
    /* ----------------------------------------------
     * Category Related Actions:
     * - List all categories
     * - Add a category
     * - Modify a category
     * - Hide a category
     * ----------------------------------------------
    */

    
    public class CategoryController : Controller
    {
        private readonly CategoryDbService _service = new CategoryDbService();
        private readonly SubcategoryDbService _subcat_svc = new SubcategoryDbService();
        // GET: Category/List
        [UserAuthorization("admin")]
        public ActionResult List()
        {
            var categoryList = _service.GetCategoryList();
            return View(categoryList);
        }

        // GET: Category/Add
        [UserAuthorization("admin")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Category/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Add([Bind(Include = "Name, ShortName")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (_service.AlreadyhastheName(category))
                {
                    ViewBag.error = "This category already been added, please try to add another category.";
                    return View(category);
                }
                if (_service.AlreadyhastheShortName(category))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(category);
                }
                _service.AddCategory(category);
                return RedirectToAction("List");
            }
            
            return View(category);
        }

        // GET: Category/Modify/5
        [UserAuthorization("admin")]
        public ActionResult Modify(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = _service.GetCategory((int) id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //POST: Category/Modify/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Modify([Bind(Include = "Id, Name, ShortName")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (_service.AlreadyhastheName(category))
                {
                    ViewBag.error = "This category already been added, please try to add another category.";
                    return View(category);
                }
                if (_service.AlreadyhastheShortName(category))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(category);
                }
                var oldCategory = _service.GetCategory(category.Id);
                oldCategory.Name = category.Name;
                oldCategory.ShortName = category.ShortName;
                _service.UpdateCategory();
                return RedirectToAction("List");
            }
            return View(category);
        }

        // GET: Category/Hide/5
        [UserAuthorization("admin")]
        public ActionResult Hide(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = _service.GetCategory((int)id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Hide", category);
        }

        // POST: Category/Hide/5
        [HttpPost, ActionName("Hide")]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult HideConfirmed(int id)
        {
            _service.HideCategory(id);
            return new HttpStatusCodeResult(HttpStatusCode.NoContent);
        }

        [UserAuthorization("user")]
        public JsonResult GetSubList(int id)
        {
            var subcategoryList = _subcat_svc.GetSubcategoryListByCat(id);
            var data = subcategoryList.Select(subcat => new SubcategoryViewModels { Id = subcat.Id, Name = subcat.Name });
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using System.Net;

namespace UI.Controllers
{
    /* ------------------------------
     * Subcategory Related Actions:
     * - List all subcategories
     * - Add a subcategory
     * - Modify a subcategory
     * - Hide a subcategory
     * ------------------------------
     */
    [RoutePrefix("Category")]
    [UserAuthorization("admin")]
    public class SubcategoryController : Controller
    {
        private readonly CategoryDbService _cat_service = new CategoryDbService();
        private readonly SubcategoryDbService _subcat_service = new SubcategoryDbService();
        [HttpPost]
        [Route("Subcategory/GetByCat")]
        public JsonResult GetByCat(int catId)
        {
            var category = _cat_service.GetCategory(catId);
            var subcatList = category.Subcategories.Where(subcat => !subcat.isHidden).ToList();
            return Json(subcatList);
        }



        // GET: Category/1/Subcategory/List
        [Route("{catId:int}/Subcategory/List")]
        public ActionResult List(int catId)
        {
            var category = _cat_service.GetCategory(catId);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoryName = category.Name;
            var subcatList = category.Subcategories.Where(subcat => !subcat.isHidden).ToList();
            return View(subcatList);
        }

        // GET: Category/1/Subcategory/Add
        [Route("{catId:int}/Subcategory/Add")]
        public ActionResult Add(int catId)
        {
            var category = _cat_service.GetCategory(catId);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View();
        }

        // POST: Category/1/Subcategory/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{catId:int}/Subcategory/Add")]
        public ActionResult Add(int catId, [Bind(Include = "Name, ShortName")] Subcategory subcategory)
        {
            if (ModelState.IsValid)
            {
                if (_subcat_service.AlreadyhastheName(catId,subcategory))
                {
                    ViewBag.error = "This subcategory already been added, please try to add another subcategory.";
                    return View(subcategory);
                }
                if (_subcat_service.AlreadyhastheShortName(catId, subcategory))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(subcategory);
                }
                subcategory.CategoryId = catId;
                _subcat_service.AddSubcategory(subcategory);
                return RedirectToAction("List");
            }
            return View(subcategory);
        }

        // GET: Category/1/Subcategory/Modify/5
        [Route("{catId:int}/Subcategory/Modify/{id:int}")]
        public ActionResult Modify(int catId, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subcategory = _subcat_service.GetSubcategory((int)id, catId);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return View(subcategory);
        }

        //POST: Category/1/Subcategory/Modify/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{catId:int}/Subcategory/Modify/{id:int}")]
        public ActionResult Modify(int catId, [Bind(Include = "Id,CategoryId,Name,ShortName")] Subcategory subcategory)
        {
            if (ModelState.IsValid)
            {
                if (_subcat_service.AlreadyhastheName(catId, subcategory))
                {
                    ViewBag.error = "This subcategory already been added, please try to add another subcategory.";
                    return View(subcategory);
                }
                if (_subcat_service.AlreadyhastheShortName(catId, subcategory))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(subcategory);
                }
                var oldSubcategory = _subcat_service.GetSubcategory(subcategory.Id, subcategory.CategoryId);
                oldSubcategory.Name = subcategory.Name;
                oldSubcategory.ShortName = subcategory.ShortName;
                _subcat_service.UpdateSubcategory();
                return RedirectToAction("List");
            }
            return View(subcategory);
        }

        // GET: Category/1/Subcategory/Hide/5
        [Route("{catId:int}/Subcategory/Hide/{id:int}")]
        public ActionResult Hide(int catId, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subcategory = _subcat_service.GetSubcategory((int)id, catId);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Hide", subcategory);
        }

        // POST: Category/1/Subcategory/Hide/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{catId:int}/Subcategory/Hide/{id:int}")]
        public ActionResult HideConfirmed(int catId, int id)
        {
            _subcat_service.HideSubcategory(id, catId);
            return new HttpStatusCodeResult(HttpStatusCode.NoContent);
        }
    }
}

UI/Views/Category/Add.cshtml
@model Data.Models.Category

@{
    ViewBag.Title = "Add Category";
}

<h2>Add a Category</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>New Category</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
        </div>
    </div>
    <h4 class=" alert-danger">@ViewBag.error</h4>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

UI/Views/Category/List.cshtml
@model IEnumerable<Data.Models.Category>
@{
    ViewBag.Title = "Category List";
}

<h2>Category List</h2>
<p>
    @Html.ActionLink("Add New Category", "Add")
</p>
<table class="table" id="list">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortName)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortName)
            </td>
            <td>
                @Html.ActionLink("Modify", "Modify", new { id = item.Id }) |
                <!-- Button trigger modal -->
                <button style="padding: 0" class="btn-link" data-toggle="modal" data-target="#myModal" data-url="@Url.Action("Hide", new { id = item.Id})">
                    Hide
                </button>
                |@Html.ActionLink("Subcategories", "List", "Subcategory", new { catId = item.Id }, null)
            </td>
        </tr>
    }
</table>

@Html.Partial("~/Views/Shared/_Modal.cshtml")

@section scripts {
    <script src="~/Scripts/modal.confirm.js"></script>
}

UI/Views/Category/Modify.cshtml
@model Data.Models.Category

@{
    ViewBag.Title = "Modify";
}

<h2>Modify @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Category</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
        </div>
    </div>
    <h4 class=" alert-danger">@ViewBag.error</h4>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

UI/Views/Category/_Hide.cshtml
@model Data.Models.Category
<h3 class="text-center">Are you sure you want to hide this category?</h3>
<div style="margin: 20px 50px;">
    <dl class="row">
        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>

        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.ShortName)
        </dd>

    </dl>
</div>