UI/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using System.Net;

namespace UI.Controllers
{
    /* ----------------------------------------------
      * Area Related Actions:
      * - List all areas including locales
      * - Add an area
      * - Modify an area
      * - Hide an area
      * ----------------------------------------------
     */

    
    public class AreaController : Controller
    {
        private readonly AreaDbService _area = new AreaDbService();
        private readonly LocationDbService _loc = new LocationDbService();
        // GET: Area/List
        [UserAuthorization("admin")]
        public ActionResult List()
        {
            return View(_area.GetAreaList());
        }

        // GET: Area/Add
        [UserAuthorization("admin")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Area/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Add([Bind(Include = "Id,Name,ShortName")] Area area)
        {
            if (ModelState.IsValid)
            {
                if (_area.AlreadyhastheName(area))
                 {
                    ViewBag.error = "This area already been added, please try to add another area.";
                    return View(area);
                 }
                if (_area.AlreadyhastheShortName(area))
                 {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(area);
                 }
                _area.AddArea(area);
                return RedirectToAction("List");
            }
            return View(area);
        }

        // GET: Area/Modify/5
        [UserAuthorization("admin")]
        public ActionResult Modify(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = _area.GetArea(id.Value);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        //POST: Area/Modify/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult Modify([Bind(Include = "Id,Name,ShortName")] Area area)
        {
            if (ModelState.IsValid)
            {

                if (_area.AlreadyhastheName(area))
                {
                    ViewBag.error = "This area already been added, please try to add another area.";
                    return View(area);
                }
                if (_area.AlreadyhastheShortName(area))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(area);
                }
                _area.ModifyArea(area);
                return RedirectToAction("List");
            }
            return View(area);
        }

        // GET: Area/Hide/5
        [UserAuthorization("admin")]
        public ActionResult Hide(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = _area.GetArea(id.Value);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Area/Hide/5
        [HttpPost, ActionName("Hide")]
        [ValidateAntiForgeryToken]
        [UserAuthorization("admin")]
        public ActionResult HideConfirmed(int id)
        {
            _area.HideArea(id);
            return RedirectToAction("List");
        }

        [UserAuthorization("user")]
        public JsonResult GetSubList(int id)
        {
            var locationList = _loc.GetLocationList(id);
            var data = locationList.Select(loc => new LocationViewModels { Id = loc.Id, Name = loc.Name });
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using System.Net;

namespace UI.Controllers
{
   /*------------------------------
    * Locale Related Actions:
    * - Add a location
    * - Modify a locale
    * - Hide a locale
    * ------------------------------
    */

    //[RoutePrefix("Area")]
    [UserAuthorization("admin")]
    public class LocationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        LocationDbService _location = new LocationDbService();
        // GET: Area/1/List
        public ActionResult List(int areaid)
        {
            return View(_location.GetLocationList(areaid));
        }

        // GET: Area/1/Locale/Add
       // [Route("{areaId:int}/Locale/Add")]
        public ActionResult Add(int areaid)
        {
            return View();
        }

        // POST: Area/1/Locale/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
       // [Route("{areaId:int}/Locale/Add")]
        public ActionResult Add(int areaid, [Bind(Include = "Id,Name,ShortName")] Location location)
        {
            if (ModelState.IsValid)
            {
                if (_location.AlreadyhastheName(areaid,location))
                {
                    ViewBag.error = "This locale already been added, please try to add another locale.";
                    return View(location);
                }
                if (_location.AlreadyhastheShortName(areaid,location))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(location);
                }
                _location.AddLocation(areaid,location);
                return RedirectToAction("List");
            }
            return View(location);
        }

        // GET: Area/1/Locale/Modify/5
        //[Route("{areaId:int}/Locale/Modify/{id:int}")]
        public ActionResult Modify(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = _location.GetLocation(id.Value);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //POST: Area/1/Locale/Modify/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Route("{areaId:int}/locale/Modify/{id:int}")]
        public ActionResult Modify(int areaid,[Bind(Include = "Id,Name,ShortName")] Location location)
        {
            if (ModelState.IsValid)
            {
                if (_location.AlreadyhastheName(areaid, location))
                {
                    ViewBag.error = "This locale already been added, please try to add another locale.";
                    return View(location);
                }
                if (_location.AlreadyhastheShortName(areaid, location))
                {
                    ViewBag.error = "This shortname already been used, please try another shortname.";
                    return View(location);
                }
                _location.ModifyLocation(location);
                return RedirectToAction("List");
            }
            return View(location);
        }

        // GET: Area/1/Locale/Hide/5
        //[Route("{areaId:int}/Locale/Hide/{id:int}")]
        public ActionResult Hide(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location= _location.GetLocation(id.Value);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Area/1/Locale/Hide/5
        [HttpPost, ActionName("Hide")]
        [ValidateAntiForgeryToken]
        //[Route("{areaId:int}/Locale/Hide/{id:int}")]
        public ActionResult HideConfirmed(int id)
        {
            _location.HideLocation(id);
            return RedirectToAction("List");
        }
    }
}

UI/Views/Area/Add.cshtml
@model Data.Models.Area

@{
    ViewBag.Title = "Add New Area";
}

<h2>Add New Area</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Area</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
        </div>
    </div>

    <h4 class=" alert-danger">@ViewBag.error</h4>

    @Html.Hidden("Hide", false)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UI/Views/Area/Hide.cshtml
@model Data.Models.Area

@{
    ViewBag.Title = "Hide";
}

<h2>Hide</h2>

<h3>Are you sure you want to hide this?</h3>
<div>
    <h4>Area</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Hide" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

UI/Views/Area/List.cshtml
@model IEnumerable<Data.Models.Area>
@{
    ViewBag.Title = "Area List";
}

<h2>Area List</h2>

<p>
    @Html.ActionLink("Add New Area", "Add")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortName)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortName)
        </td>

        <td>
            @Html.ActionLink("Modify", "Modify", new { id = item.Id }) |
            @Html.ActionLink("Hide", "Hide", new { id = item.Id }) |
            @Html.ActionLink("Locales", "List", "Location", new { areaid = item.Id }, null)
        </td>
    </tr>
    }

</table>

UI/Views/Area/Modify.cshtml
@model Data.Models.Area

@{
    ViewBag.Title = "Modify";
}

<h2>Modify Area</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Area</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
        </div>
    </div>

    <h4 class=" alert-danger">@ViewBag.error</h4>
    @Html.HiddenFor(model => model.Hide)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}