UI/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DB.Database;
using Data.Models;
using PagedList;
using Microsoft.AspNet.Identity;

namespace UI.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private MessageDbService _service = new MessageDbService();
        private UserDbService _userService = new UserDbService();
        private PostDbService _postService = new PostDbService();

        [Authorize]
        [Route("Message/ListReceived/{user_id}/{sort_order?}")]
        public ActionResult ListReceived(string user_id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var messages = _service.GetReceivedMessageByUser(user_id);
            if (!String.IsNullOrEmpty(searchString))
            {
                messages = messages.Where(s => s.Body.Contains(searchString)
                                       || s.Title.Contains(searchString)
                                       || s.Post.Title.Contains(searchString)
                                       || s.Post.Body.Contains(searchString)
                                       || s.Receiver.Email.Contains(searchString)
                                       || s.Author.Email.Contains(searchString)
                                       );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    messages = messages.OrderByDescending(s => s.PostId);
                    break;
                case "Date":
                    messages = messages.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    messages = messages.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    //messages = messages.OrderBy(s => s.PostId);
                    break;
            }
            //var list = messages.ToList();
            //int pageSize = (int)Math.Ceiling(messages.Count() / 20.0);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(messages.ToPagedList(pageNumber, pageSize));
            //return View(list);
        }



        [Authorize]
        [Route("Message/ListSent/{user_id}/{sort_order?}")]
        public ActionResult ListSent(string user_id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var messages = _service.GetSentMessageByUser(user_id);
            if (!String.IsNullOrEmpty(searchString))
            {
                messages = messages.Where(s => s.Body.Contains(searchString)
                || s.Title.Contains(searchString)
                || (s.Post != null && s.Post.Title.Contains(searchString))
                || s.Receiver.Email.Contains(searchString)
                || s.Author.Email.Contains(searchString)
                );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    messages = messages.OrderByDescending(s => s.PostId);
                    break;
                case "Date":
                    messages = messages.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    messages = messages.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    //messages = messages.OrderBy(s => s.PostId);
                    break;
            }
            //var list = messages.ToList();
            //int pageSize = (int)Math.Ceiling(messages.Count() / 20.0);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(messages.ToPagedList(pageNumber, pageSize));
            //return View(list);
        }




        [Authorize]
        [HttpGet]
        [Route("Message/MarkAllRead/{user_id}")]
        public ActionResult MarkAllRead(string user_id, bool is_all = false)
        {
            _service.MarkAllRead(user_id);
            if (is_all)
            {
                return RedirectToAction("List", new { user_id = user_id });
            }
            else
            {

                return RedirectToAction("ListUnread", new { user_id = user_id });
            }
        }




        [Authorize]
        [Route("Message/CreateManyMessages/{user_id}/{message_id}/{sort_order?}")]
        public ActionResult CreateManyMessages(int message_id, string user_id)
        {
            FakeModelGenerator.GenerateMessageForDialog(message_id);
            return RedirectToAction("Expand", new { user_id = user_id, message_id = message_id });
        }

        [Authorize]
        [Route("Message/Expand/{user_id}/{message_id}/{sort_order?}")]
        public ActionResult Expand(string user_id, int message_id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            // expand would mark as read
            var m = _service.GetMessage(message_id);
            ViewBag.Post = m.Post;
            ViewBag.PostId = m.PostId;
            if (m.AuthorId == user_id)
            {
                ViewBag.ReceiverId = m.ReceiverId;
            } else
            {
                ViewBag.ReceiverId = m.AuthorId;
            }
            if (m.ReceiverId == User.Identity.GetUserId())
            {
                m.IsRead = true;
                _service.UpdateMessage(m);
            }
            var messages = _service.GetMessageContext(message_id);
            if (!String.IsNullOrEmpty(searchString))
            {
                messages = messages.Where(s => s.Body.Contains(searchString)
                                       || s.Title.Contains(searchString)
                || (s.Post != null && s.Post.Title.Contains(searchString))
                                       || s.Receiver.Email.Contains(searchString)
                                       || s.Author.Email.Contains(searchString)
                                       );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    messages = messages.OrderByDescending(s => s.PostId);
                    break;
                case "Date":
                    messages = messages.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    messages = messages.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    //messages = messages.OrderBy(s => s.PostId);
                    break;
            }

            //int pageSize = (int)Math.Ceiling(messages.Count() / 20.0);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(messages.ToPagedList(pageNumber, pageSize));
        }


        [Authorize]
        [Route("Message/MarkPageReadInUnread/{user_id}/{sort_order?}")]
        public ActionResult MarkPageReadInUnread(string user_id, string sortOrder, string currentFilter, int page)
        {
            if (page == 0)
            {
                return RedirectToAction("ListUnread");
            }
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var searchString = currentFilter;
            ViewBag.CurrentFilter = searchString;
            var messages = _service.GetUnreadMessageByUser(user_id);
            if (!String.IsNullOrEmpty(searchString))
            {
                messages = messages.Where(s => s.Body.Contains(searchString)
                                       || s.Title.Contains(searchString)
                                    || (s.Post != null && s.Post.Title.Contains(searchString))
                                       //|| s.Post.Body.Contains(searchString)
                                       || s.Receiver.Email.Contains(searchString)
                                       || s.Author.Email.Contains(searchString)
                                       );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    messages = messages.OrderByDescending(s => s.PostId);
                    break;
                case "Date":
                    messages = messages.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":

UI/Views/Message/Create.cshtml
@model Data.Models.Message
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Create";
    var authorId = User.Identity.GetUserId();
}

<h2>Reply</h2>
<div>
    @Html.ActionLink("Back to List", "ListAll","Post")
</div>

@using (Html.BeginForm("Create","Message"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("Timestamp", DateTime.Now)
    @Html.Hidden("IsRead", false)
    @Html.Hidden("ReceiverId", ViewBag.Receiver as String)
    @Html.Hidden("PostId", ViewBag.PostId as String)
    @Html.Hidden("OrderId", 0)
    @Html.Hidden("AuthorId", authorId)

    <div class="col-xs-8">
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", style = "max-width: 100%;" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control", rows = 20, style = "max-width: 100%; resize: vertical;" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-md-4">
                <input type="submit" value="Reply" class="btn btn-primary" style="width: 200px;height: 40px;margin-top: 50px;" />
            </div>
        </div>
    </div>

    
</div>
}

UI/Views/Message/Delete.cshtml
@model Data.Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timestamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsRead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiverId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiverId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UI/Views/Message/Details.cshtml
@model Data.Models.Message

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timestamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsRead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiverId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiverId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UI/Views/Message/Expand.cshtml
@model PagedList.IPagedList<Data.Models.Message>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Chat.css" rel="stylesheet" type="text/css" />
@using Microsoft.AspNet.Identity;
@{
    var user_id = User.Identity.GetUserId();
}
@{
    ViewBag.Title = "List";
}
<h2>Message Dialog</h2>

<p>
    @Html.ActionLink("Back to Inbox", "ListReceived")
</p>
<p>
    @Html.ActionLink("Create Many Messages(Test))", "CreateManyMessages")
</p>

@if (ViewBag.Post != null && !ViewBag.Post.IsHidden)
{
    <th>
        @*@Html.DisplayNameFor(model => model.Post.Title)*@
        @Html.ActionLink("See this Post", "Details", "Post", new { id = (int)ViewBag.PostId }, null)
    </th>
}


@foreach (var item in Model)
{
    <div class="row" style="margin-left: 2px;">
        @if (item.AuthorId == user_id)
        {
            var time = item.Timestamp.ToString("h:mm tt MM/dd/yyyy");
            <div class="chatcontainer col-xs-5 col-xs-offset-7">
                <span class="time-right">You</span>
                @*<span class="time-left">@Html.DisplayFor(modelItem => item.Title)</span>*@
                <div class="clearfix"></div>
                <p>@Html.DisplayFor(modelItem => item.Body)</p>
                <span class="time-right"> @Html.DisplayFor(modelItem => time)</span>
            </div>

        }
        else
        {
            var time = item.Timestamp.ToString("h:mm tt MM/dd/yyyy");
            <div class="chatcontainer col-xs-5">
                <p class="time-left">@Html.DisplayFor(modelItem => item.Author.Email)</p>
                @*<span class="time-left">@Html.DisplayFor(modelItem => item.Author.Email)</span>*@
                @*<span class="time-right">@Html.DisplayFor(modelItem => item.Title)</span>*@
                <div class="clearfix"></div>
                <p class="message-content">@Html.DisplayFor(modelItem => item.Body)</p>
                <span class="time-left"> @Html.DisplayFor(modelItem => time)</span>
            </div>

        }
    </div>
}
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Expand",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

UI/Views/Message/List.cshtml
@*@model IEnumerable<Data.Models.Message>*@
@model PagedList.IPagedList<Data.Models.Message>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "List";
}

<h2>All Messages</h2>
<p>Hint: Use search box to search message, post and users information. Click Expand to see only dialog context.</p>


@using (Html.BeginForm("List", "Message", FormMethod.Get))
{
    <p>
        Search by post, user and content: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />


    </p>
}

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Author.Email)*@
            Sender
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Post.Title)*@
            @Html.ActionLink("Post Title", "List", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Receiver.Email)*@
            Receiver
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Timestamp)*@
            @Html.ActionLink("Date", "List", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Message Title
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Body)*@
            Message Body
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.IsRead)*@
            Message Status
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.OrderId)
                Message Order
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Receiver.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRead)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>*@
            <td>
                @Html.ActionLink("Expand", "Expand", new { message_id = item.Id }) 
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("List",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

UI/Views/Message/ListReceived.cshtml
@*@model IEnumerable<Data.Models.Message>*@
@model PagedList.IPagedList<Data.Models.Message>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "List";
}

<h2>Received Messages</h2>
<p>Hint: Use search box to search message, post and users information. Click Expand to see only dialog context and the message would be automatically read.</p>

<p>
    @Html.ActionLink("Mark All as Read", "MarkAllRead", new { is_all=true }) 
</p>



@using (Html.BeginForm("List", "Message", FormMethod.Get))
{
    <p>
        Search by post, user and content: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />


    </p>
}


<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Author.Email)*@
            Sender
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Post.Title)*@
            @Html.ActionLink("Post Title", "List", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Timestamp)*@
            @Html.ActionLink("Date", "List", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Message Title
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Body)*@
            Message Body
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.IsRead)*@
            Message Status
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.OrderId)
                Message Order
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRead)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>*@
            <td>
                @Html.ActionLink("Expand", "Expand", new { message_id = item.Id }) 
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ListReceived",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

UI/Views/Message/ListSent.cshtml
@*@model IEnumerable<Data.Models.Message>*@
@model PagedList.IPagedList<Data.Models.Message>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "List";
}

<h2>Sent Messages</h2>
<p>Hint: Use search box to search message, post and users information. Click Expand to see only dialog context.</p>


@using (Html.BeginForm("List", "Message", FormMethod.Get))
{
    <p>
        Search by post, user and content: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />


    </p>
}


<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Post.Title)*@
            @Html.ActionLink("Post Title", "List", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Receiver.Email)*@
            Receiver
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Timestamp)*@
            @Html.ActionLink("Date", "List", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Message Title
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Body)*@
            Message Body
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.OrderId)
                Message Order
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Receiver.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>*@
            <td>
                @Html.ActionLink("Expand", "Expand", new { message_id = item.Id }) 
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ListSent",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

UI/Views/Message/ListUnread.cshtml
@*@model IEnumerable<Data.Models.Message>*@
@model PagedList.IPagedList<Data.Models.Message>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "List";
}
<h2>Unread Messages</h2>
<p>Hint: Use search box to search message, post and users information. Click Expand to see only dialog context and the message would be automatically read.</p>
<p>
    @Html.ActionLink("Mark All as Read", "MarkAllRead", new { is_all = true })
</p>


@using (Html.BeginForm("List", "Message", FormMethod.Get))
{
    <p>
        Search by post, user and content: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />

    </p>
}


<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Author.Email)*@
            Sender
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Post.Title)*@
            @Html.ActionLink("Post Title", "List", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Timestamp)*@
            @Html.ActionLink("Date", "List", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Message Title
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Body)*@
            Message Body
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.IsRead)*@
            Message Status
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.OrderId)
                Message Order
            </th>*@
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Receiver.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRead)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>*@
            <td>
                @Html.ActionLink("Expand", "Expand", new { message_id = item.Id })
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("List",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))